INSERT INTO NLP_DOCS(NC_SOURCE_ID,NC_PT_MRN,NC_DOS,NC_SOURCE,NC_TYPE,NC_SUBTYPE,
NC_VERSION, NC_CLCONT, NC_MD5_DOC_HASH, NC_IMPORT_ANALYSIS,NC_MEDICS_ARRIVAL_TIME)
VALUES (?,?,?,?,?,?,?,?,?,?,SYSDATE) 
