--------------------------------------------------------
--  File created - Thursday-March-09-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table NLP_ANALYSIS
--------------------------------------------------------

  CREATE TABLE "MEDICS"."NLP_ANALYSIS" 
   (	"ANALYSIS_ID" NUMBER(*,0), 
	"ANALYSIS_DESCRIPTION" VARCHAR2(4000 BYTE) DEFAULT 'Unknown', 
	"ANALYSIS_TYPE" VARCHAR2(4000 BYTE), 
	"ANALYSIS_SOFTWARE" VARCHAR2(4000 BYTE), 
	"ANALYSIS_SOFTWARE_VERSION" VARCHAR2(4000 BYTE), 
	"ANALYSIS_CONCEPT_FILTER" VARCHAR2(4000 BYTE) DEFAULT 'UMLS', 
	"ANALYSIS_START_DATE" TIMESTAMP (6), 
	"ANALYSIS_DATASET" NUMBER, 
	"PROCESSING_TIME" NUMBER, 
	"MACHINE" VARCHAR2(255 BYTE) DEFAULT 'Unknown', 
	"THREAD_COUNT" NUMBER DEFAULT 1, 
	"ANNOTATOR_ID" NUMBER, 
	"ANNOTATOR_ANALYSIS_SEED" NUMBER, 
	"ANALYSIS_STOP_DATE" TIMESTAMP (6), 
	"ANALYSIS_STATUS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01" ;

   COMMENT ON COLUMN "MEDICS"."NLP_ANALYSIS"."ANALYSIS_DESCRIPTION" IS 'Description of analysis';
   COMMENT ON COLUMN "MEDICS"."NLP_ANALYSIS"."ANALYSIS_TYPE" IS 'Type of NLP analysis, examples would be "Pathology Note  Information Extraction", "Generic Cancer Information Extraction", "Share Clef 2013 Disease Information Extraction", "Patient Tracking List Information Extraction".';
   COMMENT ON COLUMN "MEDICS"."NLP_ANALYSIS"."ANALYSIS_SOFTWARE" IS 'The software used, ex) MMTx, cTakes, can be a full description';
   COMMENT ON COLUMN "MEDICS"."NLP_ANALYSIS"."ANALYSIS_CONCEPT_FILTER" IS 'Database used by the analysis program if any, including what subset and what year';
   COMMENT ON COLUMN "MEDICS"."NLP_ANALYSIS"."ANALYSIS_START_DATE" IS 'Timestamp when analysis started';
   COMMENT ON COLUMN "MEDICS"."NLP_ANALYSIS"."ANALYSIS_DATASET" IS 'Describe the docset this analysis was run on, FK to docset_id';
   COMMENT ON COLUMN "MEDICS"."NLP_ANALYSIS"."PROCESSING_TIME" IS 'In microseconds.';
   COMMENT ON COLUMN "MEDICS"."NLP_ANALYSIS"."MACHINE" IS 'The machine or head node the analysis was run on.';
   COMMENT ON COLUMN "MEDICS"."NLP_ANALYSIS"."THREAD_COUNT" IS 'Number of threads used, the processingUnitThreadCount not the CAS pool size.';
   COMMENT ON COLUMN "MEDICS"."NLP_ANALYSIS"."ANALYSIS_STOP_DATE" IS 'When the analysis finishes running, successfully or not.';
   COMMENT ON COLUMN "MEDICS"."NLP_ANALYSIS"."ANALYSIS_STATUS" IS '1 = fail, 2 = partial success, 3 = success. Should be foreign key to CV at some point.';
--------------------------------------------------------
--  DDL for Table NLP_ANNOTATION
--------------------------------------------------------

  CREATE TABLE "MEDICS"."NLP_ANNOTATION" 
   (	"ANNOTATION_ID" NUMBER, 
	"DOCUMENT_ID" NUMBER, 
	"ANNOTATOR_ID" NUMBER, 
	"CONCEPT_HIT_ID" NUMBER, 
	"TYPE" VARCHAR2(255 BYTE), 
	"TEXT" VARCHAR2(3999 BYTE), 
	"CUI" VARCHAR2(255 BYTE), 
	"CONCEPT_TEXT" VARCHAR2(255 BYTE), 
	"REFERS_TO_FAMILY_MEMBER" VARCHAR2(1 CHAR) DEFAULT 'N', 
	"NEGATED" VARCHAR2(1 CHAR) DEFAULT 'N', 
	"BASE_SPAN_ID" NUMBER, 
	"ANNOTATION_DATE" TIMESTAMP (6), 
	"CONCEPT_VALIDATED" CHAR(1 BYTE) DEFAULT 'N', 
	"BOUNDARY_VALIDATED" CHAR(1 BYTE) DEFAULT 'N', 
	"DOCSET_WORK_ID" NUMBER, 
	"CUI_CHANGED" CHAR(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01" ;

   COMMENT ON COLUMN "MEDICS"."NLP_ANNOTATION"."CONCEPT_HIT_ID" IS 'used to join with nlp_hits_extended.hit_id';
   COMMENT ON COLUMN "MEDICS"."NLP_ANNOTATION"."CUI" IS 'Original CUI from NLP_HITS_EXTENDED';
   COMMENT ON COLUMN "MEDICS"."NLP_ANNOTATION"."ANNOTATION_DATE" IS 'Time annotation was created.';
   COMMENT ON COLUMN "MEDICS"."NLP_ANNOTATION"."CONCEPT_VALIDATED" IS 'Concept was validated by a human annotator';
   COMMENT ON COLUMN "MEDICS"."NLP_ANNOTATION"."BOUNDARY_VALIDATED" IS 'Annotator validated boundary';
   COMMENT ON COLUMN "MEDICS"."NLP_ANNOTATION"."CUI_CHANGED" IS 'flagged if a different CUI has been selected. ';
--------------------------------------------------------
--  DDL for Table NLP_ANNOTATOR
--------------------------------------------------------

  CREATE TABLE "MEDICS"."NLP_ANNOTATOR" 
   (	"ANNOTATOR_ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE), 
	"USERNAME" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"IS_ADMIN" CHAR(1 CHAR) DEFAULT 'N', 
	"DEFAULT_ANALYSIS" NUMBER(*,0), 
	"DEFAULT_DOCSET" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01" ;

   COMMENT ON COLUMN "MEDICS"."NLP_ANNOTATOR"."IS_ADMIN" IS 'N = default user Y is admin user';

--------------------------------------------------------
--  DDL for Table NLP_DOC_HISTORY
--------------------------------------------------------

  CREATE TABLE "MEDICS"."NLP_DOC_HISTORY" 
   (	"DOCUMENT_ID" NUMBER, 
	"ANALYSIS_ID" NUMBER, 
	"DOC_START_TIME" TIMESTAMP (6), 
	"DOC_FINISH_TIME" TIMESTAMP (6), 
	"CAS" CLOB, 
	"STATUS_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01" 
 LOB ("CAS") STORE AS BASICFILE (
  TABLESPACE "MEDICS_DATA01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "MEDICS"."NLP_DOC_HISTORY"."DOCUMENT_ID" IS 'Foreign key to NLP_DOCS';
   COMMENT ON COLUMN "MEDICS"."NLP_DOC_HISTORY"."ANALYSIS_ID" IS 'Foreign key to NLP_ANALYSIS';
   COMMENT ON COLUMN "MEDICS"."NLP_DOC_HISTORY"."DOC_FINISH_TIME" IS '';
   COMMENT ON COLUMN "MEDICS"."NLP_DOC_HISTORY"."CAS" IS 'The result of the analysis in CAS (XMI) form.';
   COMMENT ON COLUMN "MEDICS"."NLP_DOC_HISTORY"."STATUS_ID" IS 'A primary key to the doc status table.';
--------------------------------------------------------
--  DDL for Table NLP_DOC_STATUS
--------------------------------------------------------

  CREATE TABLE "MEDICS"."NLP_DOC_STATUS" 
   (	"DOC_STATUS_ID" NUMBER, 
	"STATUS" VARCHAR2(255 CHAR), 
	"DESCRIPTION" VARCHAR2(100 BYTE), 
	"ERROR_MESSAGE" VARCHAR2(3999 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01" ;

   COMMENT ON COLUMN "MEDICS"."NLP_DOC_STATUS"."STATUS" IS 'What action to take, ex) "OK", "RERUN", "IGNORE"';
--------------------------------------------------------
--  DDL for Table NLP_DOCS
--------------------------------------------------------

  CREATE TABLE "MEDICS"."NLP_DOCS" 
   (	"NC_REPORTID" NUMBER, 
	"NC_CLCONT" CLOB, 
	"NC_PT_MRN" VARCHAR2(12 BYTE), 
	"NC_DOS" DATE, 
	"NC_SOURCE" VARCHAR2(128 BYTE), 
	"NC_TYPE" VARCHAR2(100 BYTE), 
	"NC_SUBTYPE" VARCHAR2(128 BYTE), 
	"NC_VERSION" NUMBER, 
	"NC_MEDICS_ARRIVAL_TIME" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"NC_SOURCE_ID" VARCHAR2(255 BYTE), 
	"NC_JAVAHASHCODE" NUMBER, 
	"NC_IMPORT_ANALYSIS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01" 
 LOB ("NC_CLCONT") STORE AS BASICFILE "SYS_LOB0000373886C00002$$"(
  TABLESPACE "MEDICS_DATA01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "MEDICS"."NLP_DOCS"."NC_REPORTID" IS 'Primary key generated from sequence';
   COMMENT ON COLUMN "MEDICS"."NLP_DOCS"."NC_PT_MRN" IS 'Documents from Careflow contain leading 0''s, those from ICDA do not.';
   COMMENT ON COLUMN "MEDICS"."NLP_DOCS"."NC_DOS" IS 'For Careflow, it corresponds to DATE2';
   COMMENT ON COLUMN "MEDICS"."NLP_DOCS"."NC_SOURCE" IS 'icda or cflo';
   COMMENT ON COLUMN "MEDICS"."NLP_DOCS"."NC_TYPE" IS 'Type of document as described in REPORTSOURCE from Careflow or DS_SOURCE_CODE from ICDA. Ex) PTH from DS_SOURCE_CODE in ICDA or Cquence MT from Careflow. (No longer using REPORTSOURCE from Careflow, could use workdesct description or workid)';
   COMMENT ON COLUMN "MEDICS"."NLP_DOCS"."NC_SUBTYPE" IS 'A more precise description of the document type. For documents originating from ICDA this would be DT_TYPE and for documents originating from Careflow this would be REPORTTYPE. For example GENETICS RPT.';
   COMMENT ON COLUMN "MEDICS"."NLP_DOCS"."NC_VERSION" IS 'Corresponds to the Careflow version field (1 or 2). In the case of ICDA it corresponds to DN result status.';
   COMMENT ON COLUMN "MEDICS"."NLP_DOCS"."NC_MEDICS_ARRIVAL_TIME" IS 'Date at which document was transferred from source document system (usually icda or cflo) to medics.';
   COMMENT ON COLUMN "MEDICS"."NLP_DOCS"."NC_SOURCE_ID" IS 'A non-unique identifier for the document representing the source identifier. It corresponds to DN_UNIQUE_ID in ICDA documents and REPORTID in Careflow documents.';
   COMMENT ON COLUMN "MEDICS"."NLP_DOCS"."NC_JAVAHASHCODE" IS 'Result of string.hashcode() in java 1.6+. Used to distinguish between the same source code that went through a different conversion process, ex) new version of Tika generates different text for the same original PDF document. This should be used on the string obtained by getCharacterStream() on NC_CLCONT. Not currently supposed on FIG.';
   COMMENT ON COLUMN "MEDICS"."NLP_DOCS"."NC_IMPORT_ANALYSIS" IS 'Analysis used for import, to allow provenance for TIKA version when converting BLOBs.';
--------------------------------------------------------
--  DDL for Table NLP_DOCSET
--------------------------------------------------------

  CREATE TABLE "MEDICS"."NLP_DOCSET" 
   (	"DOCSET_ID" NUMBER, 
	"DESCRIPTION" VARCHAR2(800 BYTE), 
	"GOLD_ANALYSIS_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01" ;

   COMMENT ON COLUMN "MEDICS"."NLP_DOCSET"."GOLD_ANALYSIS_ID" IS 'An analysis_id that is considered to be the gold standard for this docset';
--------------------------------------------------------
--  DDL for Table NLP_DOCSET_MAP
--------------------------------------------------------

  CREATE TABLE "MEDICS"."NLP_DOCSET_MAP" 
   (	"DOCSET_ID" NUMBER, 
	"DOCUMENT_ID" NUMBER, 
	"DOC_MRN" VARCHAR2(12 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01" ;

   COMMENT ON COLUMN "MEDICS"."NLP_DOCSET_MAP"."DOC_MRN" IS 'Medical record number of patient, prefixed with 0''s';
--------------------------------------------------------
--  DDL for Table NLP_DOCSET_WORK
--------------------------------------------------------

  CREATE TABLE "MEDICS"."NLP_DOCSET_WORK" 
   (	"DOCSET_ID" NUMBER, 
	"LAST_UPDATE" TIMESTAMP (6), 
	"ANNOTATOR_ID" NUMBER, 
	"ANALYSIS_ID" NUMBER, 
	"DOCSET_WORK_ID" NUMBER, 
	"START_DATE" TIMESTAMP (6), 
	"END_DATE" TIMESTAMP (6), 
	"STATUS" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01" ;

   COMMENT ON COLUMN "MEDICS"."NLP_DOCSET_WORK"."DOCSET_ID" IS 'last document worked on';
   COMMENT ON COLUMN "MEDICS"."NLP_DOCSET_WORK"."DOCSET_WORK_ID" IS 'primary key';
   COMMENT ON COLUMN "MEDICS"."NLP_DOCSET_WORK"."START_DATE" IS 'start working on doc set';
   COMMENT ON COLUMN "MEDICS"."NLP_DOCSET_WORK"."END_DATE" IS 'end date when docset analysis complete';
   COMMENT ON COLUMN "MEDICS"."NLP_DOCSET_WORK"."STATUS" IS 'The status of whether the annotator is still working on this docset
0 = working 
1 = complete';
--------------------------------------------------------
--  DDL for Table NLP_DOCSET_WORK_DOCS
--------------------------------------------------------

  CREATE TABLE "MEDICS"."NLP_DOCSET_WORK_DOCS" 
   (	"DOCSET_WORK_ID" NUMBER, 
	"DOCUMENT_ID" NUMBER, 
	"START_DATE" TIMESTAMP (6), 
	"END_DATE" TIMESTAMP (6), 
	"STATUS" NUMBER(*,0), 
	"ANNOTATOR_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01" ;

   COMMENT ON COLUMN "MEDICS"."NLP_DOCSET_WORK_DOCS"."STATUS" IS 'status of working on this doc.
0 = working 
1 = complete';

--------------------------------------------------------
--  DDL for Table NLP_HITS_EXTENDED
--------------------------------------------------------

  CREATE TABLE "MEDICS"."NLP_HITS_EXTENDED" 
   (	"HIT_ID" NUMBER, 
	"ANALYSIS_ID" NUMBER, 
	"DOCUMENT_ID" VARCHAR2(255 BYTE), 
	"HIT_TEXT" VARCHAR2(4000 BYTE), 
	"CONCEPT_TEXT" VARCHAR2(4000 BYTE), 
	"UMLS_CUI" VARCHAR2(20 BYTE), 
	"UMLS_SEMANTIC_TYPES" VARCHAR2(50 BYTE), 
	"SCORE" NUMBER, 
	"MRN" VARCHAR2(20 BYTE), 
	"EXTERNAL_HIT_ID" VARCHAR2(40 BYTE), 
	"HIT_TEXT_EXTENDED" VARCHAR2(4000 BYTE), 
	"IS_NEGATED" CHAR(1 BYTE), 
	"SUBJECT" VARCHAR2(20 BYTE) DEFAULT 'patient', 
	"SNOMED_ID" VARCHAR2(20 BYTE), 
	"HIT_START_CHAR_INDEX" NUMBER, 
	"LINE_START" NUMBER, 
	"IS_GENERIC" NUMBER DEFAULT 0, 
	"HIT_STOP_CHAR_INDEX" NUMBER, 
	"IS_POSSIBLE" CHAR(1 BYTE) DEFAULT 'N', 
	"DOCUMENT_SECTION_NAME" VARCHAR2(255 BYTE), 
	"LINE_STOP" NUMBER, 
	"IS_CONDITIONAL" NUMBER DEFAULT 0, 
	"MAPPING_SCORE" NUMBER, 
	"NER_TYPE" VARCHAR2(100 BYTE), 
	"COURSE" VARCHAR2(20 BYTE) DEFAULT 'unmarked', 
	"SEVERITY" VARCHAR2(20 BYTE) DEFAULT 'unmarked'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01" ;

   COMMENT ON COLUMN "MEDICS"."NLP_HITS_EXTENDED"."HIT_ID" IS 'Uses nlp_big_hits_autoincrement_seq and nlp_big_hits_autoinc_trigger to get the value';
   COMMENT ON COLUMN "MEDICS"."NLP_HITS_EXTENDED"."ANALYSIS_ID" IS 'Foreign key to analysis table describing the analysis that produced this result (algorithim, database, etc..)';
   COMMENT ON COLUMN "MEDICS"."NLP_HITS_EXTENDED"."DOCUMENT_ID" IS 'Foreign key to NLP clobs that produced the analysis.';
   COMMENT ON COLUMN "MEDICS"."NLP_HITS_EXTENDED"."HIT_TEXT" IS 'Test for which hit was generated';
   COMMENT ON COLUMN "MEDICS"."NLP_HITS_EXTENDED"."SCORE" IS 'How well the hit  text maps';
   COMMENT ON COLUMN "MEDICS"."NLP_HITS_EXTENDED"."MRN" IS 'Leading 0''s are stripped from Careflow MRNs. Do not join against NLP_DOCS without casting.';
   COMMENT ON COLUMN "MEDICS"."NLP_HITS_EXTENDED"."HIT_TEXT_EXTENDED" IS 'Document text that created the hit plus addidtional co ntextual flanking sequence, usually the sentence.';
   COMMENT ON COLUMN "MEDICS"."NLP_HITS_EXTENDED"."IS_NEGATED" IS '''Y'' or ''N''';
   COMMENT ON COLUMN "MEDICS"."NLP_HITS_EXTENDED"."SUBJECT" IS 'Was is_family with simple ''Y'' or ''N''. Now subject class with values patient, family_member, donor_family_member, donor_other, null, other.';
   COMMENT ON COLUMN "MEDICS"."NLP_HITS_EXTENDED"."SNOMED_ID" IS 'SNOMED identifier if applicable';
   COMMENT ON COLUMN "MEDICS"."NLP_HITS_EXTENDED"."HIT_START_CHAR_INDEX" IS 'Character index (iincluding non-printing characters) of start of text in the document.';
   COMMENT ON COLUMN "MEDICS"."NLP_HITS_EXTENDED"."LINE_START" IS 'Line index (starting with 1 for the first line) ofthe line containing the hit text';
   COMMENT ON COLUMN "MEDICS"."NLP_HITS_EXTENDED"."IS_GENERIC" IS 'Indicates whether this is a "generic" (not specific to patient) mention. 1 indicates this is the case, 0 indicates it is not.';
   COMMENT ON COLUMN "MEDICS"."NLP_HITS_EXTENDED"."HIT_STOP_CHAR_INDEX" IS 'Character index (iincluding non-printing characters) of stop art of text in the documet';
   COMMENT ON COLUMN "MEDICS"."NLP_HITS_EXTENDED"."IS_POSSIBLE" IS '''Y'' or ''N'' if text is possible, not definite.';
   COMMENT ON COLUMN "MEDICS"."NLP_HITS_EXTENDED"."DOCUMENT_SECTION_NAME" IS 'Name of the section of the document it came from, may eventually replaced by id#';
   COMMENT ON COLUMN "MEDICS"."NLP_HITS_EXTENDED"."LINE_STOP" IS 'Line index (starting with 1 for the first line) of the last line containing the hit text';
   COMMENT ON COLUMN "MEDICS"."NLP_HITS_EXTENDED"."IS_CONDITIONAL" IS 'A 1 indicates that this concept is conditional on another condition, 0 (default) indicates that it is not.';
   COMMENT ON COLUMN "MEDICS"."NLP_HITS_EXTENDED"."MAPPING_SCORE" IS 'Scores how well the hit maps in conjunction with other hits spanning the same phrase';
   COMMENT ON COLUMN "MEDICS"."NLP_HITS_EXTENDED"."NER_TYPE" IS 'Named Entity Recognition type, ex) Problem, Procedure, Test, Drug. Should be FK to ontology lookup. A "coase grained" concept.';
   COMMENT ON COLUMN "MEDICS"."NLP_HITS_EXTENDED"."COURSE" IS 'Course of disease: unmarked, changed, increased, decreased, improved, worsened, resolved.';
   COMMENT ON COLUMN "MEDICS"."NLP_HITS_EXTENDED"."SEVERITY" IS 'unmarked, slight, moderate, severe';

--------------------------------------------------------
--  DDL for Table NLP_REF_SEGMENT_REGEX
--------------------------------------------------------

  CREATE TABLE "MEDICS"."NLP_REF_SEGMENT_REGEX" 
   (	"SEGMENT_REGEX_ID" NUMBER, 
	"REGEX" VARCHAR2(2000 BYTE), 
	"SEGMENT_ID" VARCHAR2(256 BYTE), 
	"LIMIT_TO_REGEX" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01" ;
--------------------------------------------------------
--  DDL for Table NLP_SPAN
--------------------------------------------------------

  CREATE TABLE "MEDICS"."NLP_SPAN" 
   (	"SPAN_ID" NUMBER, 
	"SPAN_CHAR_START" NUMBER, 
	"SPAN_CHAR_END" NUMBER, 
	"DOCUMENT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01" ;
--------------------------------------------------------
--  DDL for Index NLP_ANALYSIS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MEDICS"."NLP_ANALYSIS_PK" ON "MEDICS"."NLP_ANALYSIS" ("ANALYSIS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01" ;
--------------------------------------------------------
--  DDL for Index NLP_CONCEPT_CURATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MEDICS"."NLP_CONCEPT_CURATION_PK" ON "MEDICS"."NLP_ANNOTATION" ("ANNOTATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01" ;
--------------------------------------------------------
--  DDL for Index NLP_ANNOTATOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MEDICS"."NLP_ANNOTATOR_PK" ON "MEDICS"."NLP_ANNOTATOR" ("ANNOTATOR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01" ;

--------------------------------------------------------
--  DDL for Index NLP_DOC_HISTORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MEDICS"."NLP_DOC_HISTORY_PK" ON "MEDICS"."NLP_DOC_HISTORY" ("DOCUMENT_ID", "ANALYSIS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01" ;
--------------------------------------------------------
--  DDL for Index NLP_ERRORS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MEDICS"."NLP_ERRORS_PK" ON "MEDICS"."NLP_DOC_STATUS" ("DOC_STATUS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01" ;
--------------------------------------------------------
--  DDL for Index NLP_DOCS_SOURCE_INDEX2
--------------------------------------------------------

  CREATE INDEX "MEDICS"."NLP_DOCS_SOURCE_INDEX2" ON "MEDICS"."NLP_DOCS" ("NC_SOURCE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01" ;
--------------------------------------------------------
--  DDL for Index NLP_DOCS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MEDICS"."NLP_DOCS_PK" ON "MEDICS"."NLP_DOCS" ("NC_REPORTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01" ;
--------------------------------------------------------
--  DDL for Index NLP_DOCS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "MEDICS"."NLP_DOCS_UK1" ON "MEDICS"."NLP_DOCS" ("NC_SOURCE_ID", "NC_SOURCE", "NC_VERSION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01" ;
--------------------------------------------------------
--  DDL for Index NLP_DOCS_MRN_INDEX1
--------------------------------------------------------

  CREATE INDEX "MEDICS"."NLP_DOCS_MRN_INDEX1" ON "MEDICS"."NLP_DOCS" ("NC_PT_MRN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01" ;
--------------------------------------------------------
--  DDL for Index NLP_DOCSET_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MEDICS"."NLP_DOCSET_PK" ON "MEDICS"."NLP_DOCSET" ("DOCSET_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01" ;
--------------------------------------------------------
--  DDL for Index NLP_DOCSET_MAP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MEDICS"."NLP_DOCSET_MAP_PK" ON "MEDICS"."NLP_DOCSET_MAP" ("DOCSET_ID", "DOCUMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01" ;
--------------------------------------------------------
--  DDL for Index NLP_DOCSET_WORK_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "MEDICS"."NLP_DOCSET_WORK_UK1" ON "MEDICS"."NLP_DOCSET_WORK" ("DOCSET_ID", "ANALYSIS_ID", "ANNOTATOR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01" ;
--------------------------------------------------------
--  DDL for Index NLP_DOCSET_WORK_DOCS_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "MEDICS"."NLP_DOCSET_WORK_DOCS_PK1" ON "MEDICS"."NLP_DOCSET_WORK_DOCS" ("DOCSET_WORK_ID", "ANNOTATOR_ID", "DOCUMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01" ;

--------------------------------------------------------
--  DDL for Index NLP_BIG_HITS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MEDICS"."NLP_BIG_HITS_PK" ON "MEDICS"."NLP_HITS_EXTENDED" ("HIT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01" ;
--------------------------------------------------------
--  DDL for Index NLP_HITS_EXTENDED_CUI_IDX
--------------------------------------------------------

  CREATE INDEX "MEDICS"."NLP_HITS_EXTENDED_CUI_IDX" ON "MEDICS"."NLP_HITS_EXTENDED" ("UMLS_CUI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01" ;


--------------------------------------------------------
--  DDL for Index NLP_REF_SEGMENT_REGEX_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MEDICS"."NLP_REF_SEGMENT_REGEX_PK" ON "MEDICS"."NLP_REF_SEGMENT_REGEX" ("SEGMENT_REGEX_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01" ;
--------------------------------------------------------
--  DDL for Index NLP_ANNOTATION_SPAN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MEDICS"."NLP_ANNOTATION_SPAN_PK" ON "MEDICS"."NLP_SPAN" ("SPAN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01" ;
--------------------------------------------------------
--  Constraints for Table NLP_ANALYSIS
--------------------------------------------------------

  ALTER TABLE "MEDICS"."NLP_ANALYSIS" ADD CONSTRAINT "NLP_ANALYSIS_PK" PRIMARY KEY ("ANALYSIS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01"  ENABLE;
  ALTER TABLE "MEDICS"."NLP_ANALYSIS" MODIFY ("ANALYSIS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NLP_ANNOTATION
--------------------------------------------------------

  ALTER TABLE "MEDICS"."NLP_ANNOTATION" ADD CONSTRAINT "NLP_CONCEPT_CURATION_PK" PRIMARY KEY ("ANNOTATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01"  ENABLE;
  ALTER TABLE "MEDICS"."NLP_ANNOTATION" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "MEDICS"."NLP_ANNOTATION" MODIFY ("DOCUMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "MEDICS"."NLP_ANNOTATION" MODIFY ("ANNOTATION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NLP_ANNOTATOR
--------------------------------------------------------

  ALTER TABLE "MEDICS"."NLP_ANNOTATOR" ADD CONSTRAINT "NLP_ANNOTATOR_PK" PRIMARY KEY ("ANNOTATOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01"  ENABLE;
  ALTER TABLE "MEDICS"."NLP_ANNOTATOR" MODIFY ("IS_ADMIN" NOT NULL ENABLE);
  ALTER TABLE "MEDICS"."NLP_ANNOTATOR" MODIFY ("ANNOTATOR_ID" NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table NLP_DOC_HISTORY
--------------------------------------------------------

  ALTER TABLE "MEDICS"."NLP_DOC_HISTORY" ADD CONSTRAINT "NLP_DOC_HISTORY_PK" PRIMARY KEY ("DOCUMENT_ID", "ANALYSIS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01"  ENABLE;
  ALTER TABLE "MEDICS"."NLP_DOC_HISTORY" MODIFY ("ANALYSIS_ID" NOT NULL ENABLE);
  ALTER TABLE "MEDICS"."NLP_DOC_HISTORY" MODIFY ("DOCUMENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NLP_DOC_STATUS
--------------------------------------------------------

  ALTER TABLE "MEDICS"."NLP_DOC_STATUS" ADD CONSTRAINT "NLP_ERRORS_PK" PRIMARY KEY ("DOC_STATUS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01"  ENABLE;
  ALTER TABLE "MEDICS"."NLP_DOC_STATUS" MODIFY ("DOC_STATUS_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NLP_DOCS
--------------------------------------------------------

  ALTER TABLE "MEDICS"."NLP_DOCS" ADD CONSTRAINT "NLP_DOCS_UK1" UNIQUE ("NC_SOURCE_ID", "NC_SOURCE", "NC_VERSION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01"  ENABLE;
  ALTER TABLE "MEDICS"."NLP_DOCS" ADD CONSTRAINT "NLP_DOCS_PK" PRIMARY KEY ("NC_REPORTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01"  ENABLE;
  ALTER TABLE "MEDICS"."NLP_DOCS" MODIFY ("NC_SOURCE_ID" NOT NULL ENABLE);
  ALTER TABLE "MEDICS"."NLP_DOCS" MODIFY ("NC_SOURCE" NOT NULL ENABLE);
  ALTER TABLE "MEDICS"."NLP_DOCS" MODIFY ("NC_REPORTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NLP_DOCSET
--------------------------------------------------------

  ALTER TABLE "MEDICS"."NLP_DOCSET" ADD CONSTRAINT "NLP_DOCSET_PK" PRIMARY KEY ("DOCSET_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01"  ENABLE;
  ALTER TABLE "MEDICS"."NLP_DOCSET" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "MEDICS"."NLP_DOCSET" MODIFY ("DOCSET_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NLP_DOCSET_MAP
--------------------------------------------------------

  ALTER TABLE "MEDICS"."NLP_DOCSET_MAP" ADD CONSTRAINT "NLP_DOCSET_MAP_PK" PRIMARY KEY ("DOCSET_ID", "DOCUMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01"  ENABLE;
  ALTER TABLE "MEDICS"."NLP_DOCSET_MAP" MODIFY ("DOCUMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "MEDICS"."NLP_DOCSET_MAP" MODIFY ("DOCSET_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NLP_DOCSET_WORK
--------------------------------------------------------

  ALTER TABLE "MEDICS"."NLP_DOCSET_WORK" ADD CONSTRAINT "NLP_DOCSET_WORK_UK1" UNIQUE ("DOCSET_ID", "ANALYSIS_ID", "ANNOTATOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01"  ENABLE;
  ALTER TABLE "MEDICS"."NLP_DOCSET_WORK" MODIFY ("DOCSET_WORK_ID" NOT NULL ENABLE);
  ALTER TABLE "MEDICS"."NLP_DOCSET_WORK" MODIFY ("ANALYSIS_ID" NOT NULL ENABLE);
  ALTER TABLE "MEDICS"."NLP_DOCSET_WORK" MODIFY ("ANNOTATOR_ID" NOT NULL ENABLE);
  ALTER TABLE "MEDICS"."NLP_DOCSET_WORK" MODIFY ("LAST_UPDATE" NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table NLP_HITS_EXTENDED
--------------------------------------------------------

  ALTER TABLE "MEDICS"."NLP_HITS_EXTENDED" MODIFY ("HIT_TEXT" NOT NULL ENABLE);
  ALTER TABLE "MEDICS"."NLP_HITS_EXTENDED" MODIFY ("DOCUMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "MEDICS"."NLP_HITS_EXTENDED" MODIFY ("ANALYSIS_ID" NOT NULL ENABLE);
  ALTER TABLE "MEDICS"."NLP_HITS_EXTENDED" MODIFY ("HIT_ID" NOT NULL ENABLE);


--------------------------------------------------------
--  Constraints for Table NLP_REF_SEGMENT_REGEX
--------------------------------------------------------

  ALTER TABLE "MEDICS"."NLP_REF_SEGMENT_REGEX" ADD CONSTRAINT "NLP_REF_SEGMENT_REGEX_PK" PRIMARY KEY ("SEGMENT_REGEX_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01"  ENABLE;
  ALTER TABLE "MEDICS"."NLP_REF_SEGMENT_REGEX" MODIFY ("SEGMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "MEDICS"."NLP_REF_SEGMENT_REGEX" MODIFY ("REGEX" NOT NULL ENABLE);
  ALTER TABLE "MEDICS"."NLP_REF_SEGMENT_REGEX" MODIFY ("SEGMENT_REGEX_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NLP_SPAN
--------------------------------------------------------

  ALTER TABLE "MEDICS"."NLP_SPAN" ADD CONSTRAINT "NLP_ANNOTATION_SPAN_PK" PRIMARY KEY ("SPAN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01"  ENABLE;
  ALTER TABLE "MEDICS"."NLP_SPAN" MODIFY ("SPAN_CHAR_END" NOT NULL ENABLE);
  ALTER TABLE "MEDICS"."NLP_SPAN" MODIFY ("SPAN_CHAR_START" NOT NULL ENABLE);
  ALTER TABLE "MEDICS"."NLP_SPAN" MODIFY ("SPAN_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table NLP_ANALYSIS
--------------------------------------------------------

  ALTER TABLE "MEDICS"."NLP_ANALYSIS" ADD CONSTRAINT "NLP_ANALYSIS_NLP_ANNOTATO_FK1" FOREIGN KEY ("ANNOTATOR_ID")
	  REFERENCES "MEDICS"."NLP_ANNOTATOR" ("ANNOTATOR_ID") ENABLE;
  ALTER TABLE "MEDICS"."NLP_ANALYSIS" ADD CONSTRAINT "NLP_ANALYSIS_NLP_DOCSET_FK1" FOREIGN KEY ("ANALYSIS_DATASET")
	  REFERENCES "MEDICS"."NLP_DOCSET" ("DOCSET_ID") DISABLE;
  ALTER TABLE "MEDICS"."NLP_ANALYSIS" ADD CONSTRAINT "NLP_ANALYSIS_SEED_FK1" FOREIGN KEY ("ANALYSIS_ID")
	  REFERENCES "MEDICS"."NLP_ANALYSIS" ("ANALYSIS_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NLP_ANNOTATION
--------------------------------------------------------

  ALTER TABLE "MEDICS"."NLP_ANNOTATION" ADD CONSTRAINT "NLP_ANNOTATION_NLP_SPAN_FK1" FOREIGN KEY ("BASE_SPAN_ID")
	  REFERENCES "MEDICS"."NLP_SPAN" ("SPAN_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NLP_ANNOTATOR
--------------------------------------------------------

  ALTER TABLE "MEDICS"."NLP_ANNOTATOR" ADD CONSTRAINT "NLP_ANNOTATOR_NLP_ANALYSI_FK1" FOREIGN KEY ("DEFAULT_ANALYSIS")
	  REFERENCES "MEDICS"."NLP_ANALYSIS" ("ANALYSIS_ID") ENABLE;
  ALTER TABLE "MEDICS"."NLP_ANNOTATOR" ADD CONSTRAINT "NLP_ANNOTATOR_NLP_DOCSET_FK1" FOREIGN KEY ("DEFAULT_DOCSET")
	  REFERENCES "MEDICS"."NLP_DOCSET" ("DOCSET_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NLP_DOC_HISTORY
--------------------------------------------------------

  ALTER TABLE "MEDICS"."NLP_DOC_HISTORY" ADD CONSTRAINT "NLP_DOC_HISTORY_NLP_ANALY_FK1" FOREIGN KEY ("ANALYSIS_ID")
	  REFERENCES "MEDICS"."NLP_ANALYSIS" ("ANALYSIS_ID") DISABLE;
  ALTER TABLE "MEDICS"."NLP_DOC_HISTORY" ADD CONSTRAINT "NLP_DOC_HISTORY_NLP_DOCS_FK1" FOREIGN KEY ("DOCUMENT_ID")
	  REFERENCES "MEDICS"."NLP_DOCS" ("NC_REPORTID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NLP_DOCSET_WORK
--------------------------------------------------------

  ALTER TABLE "MEDICS"."NLP_DOCSET_WORK" ADD CONSTRAINT "NLP_ANALYSIS_FK1" FOREIGN KEY ("ANALYSIS_ID")
	  REFERENCES "MEDICS"."NLP_ANALYSIS" ("ANALYSIS_ID") ENABLE;
  ALTER TABLE "MEDICS"."NLP_DOCSET_WORK" ADD CONSTRAINT "NLP_ANNOTATOR_FK1" FOREIGN KEY ("ANNOTATOR_ID")
	  REFERENCES "MEDICS"."NLP_ANNOTATOR" ("ANNOTATOR_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NLP_SPAN
--------------------------------------------------------

  ALTER TABLE "MEDICS"."NLP_SPAN" ADD CONSTRAINT "NLP_SPAN_NLP_DOCS_FK1" FOREIGN KEY ("DOCUMENT_ID")
	  REFERENCES "MEDICS"."NLP_DOCS" ("NC_REPORTID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger NLP_ANALYSIS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MEDICS"."NLP_ANALYSIS_TRG" 
 BEFORE INSERT ON NLP_ANALYSIS 
FOR EACH ROW 
BEGIN
  SELECT NLP_ANALYSIS_SEQ.NEXTVAL INTO :NEW.ANALYSIS_ID FROM DUAL;
END;



/
ALTER TRIGGER "MEDICS"."NLP_ANALYSIS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NLP_ANNOTATION_AUTOINC_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MEDICS"."NLP_ANNOTATION_AUTOINC_TRG" 
 BEFORE INSERT ON NLP_ANNOTATION
FOR EACH ROW 
BEGIN
  SELECT NLP_ANNOTATION_AUTOINC_SEQ.NEXTVAL INTO :NEW.ANNOTATION_ID FROM DUAL;
END;

/
ALTER TRIGGER "MEDICS"."NLP_ANNOTATION_AUTOINC_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NLP_ANNOTATOR_AUTOINC_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MEDICS"."NLP_ANNOTATOR_AUTOINC_TRG" 
 BEFORE INSERT ON NLP_ANNOTATOR 
FOR EACH ROW 
BEGIN
  SELECT NLP_ANNOTATOR_AUTOINC_SEQ.NEXTVAL INTO :NEW.ANNOTATOR_ID FROM DUAL;
END;

/
ALTER TRIGGER "MEDICS"."NLP_ANNOTATOR_AUTOINC_TRG" ENABLE;

--------------------------------------------------------
--  DDL for Trigger NLP_DOCS_AUTOINC_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MEDICS"."NLP_DOCS_AUTOINC_TRG" 
  BEFORE INSERT ON NLP_DOCS
  FOR EACH ROW
BEGIN
  :new.nc_reportid := nlp_docs_seq_autoinc.nextval;
END;

/
ALTER TRIGGER "MEDICS"."NLP_DOCS_AUTOINC_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NLP_DOCSET_AUTOINC_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MEDICS"."NLP_DOCSET_AUTOINC_TRG" 
BEFORE INSERT ON NLP_DOCSET 
FOR EACH ROW 
BEGIN
  SELECT NLP_DOCSET_AUTOINC_SEQ.NEXTVAL INTO :NEW.DOCSET_ID FROM DUAL;
END;

/
ALTER TRIGGER "MEDICS"."NLP_DOCSET_AUTOINC_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NLP_DOCSET_WORK_AUTOINC_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MEDICS"."NLP_DOCSET_WORK_AUTOINC_TRG" 
 BEFORE INSERT ON NLP_DOCSET_WORK 
FOR EACH ROW 
BEGIN
  SELECT NLP_DOCSET_WORK_AUTOINC_SEQ.NEXTVAL INTO :NEW.docset_work_id FROM DUAL;
END;

/
ALTER TRIGGER "MEDICS"."NLP_DOCSET_WORK_AUTOINC_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NLP_EXT_HITS_AUTOINC_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MEDICS"."NLP_EXT_HITS_AUTOINC_TRG" 
  BEFORE INSERT ON NLP_HITS_EXTENDED
  FOR EACH ROW
BEGIN
  :new.hit_id := nlp_big_hits_autoinc_seq.nextval;
END;

/
ALTER TRIGGER "MEDICS"."NLP_EXT_HITS_AUTOINC_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NLP_SPAN_AUTOINC_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MEDICS"."NLP_SPAN_AUTOINC_TRG" 
 BEFORE INSERT ON NLP_SPAN
FOR EACH ROW 
BEGIN
  SELECT NLP_SPAN_AUTOINC_SEQ.NEXTVAL INTO :NEW.SPAN_ID FROM DUAL;
END;

/
ALTER TRIGGER "MEDICS"."NLP_SPAN_AUTOINC_TRG" ENABLE;



--------------------------------------------------------
--  DDL for Table IDENTIFIED_ANNOTATION
--------------------------------------------------------

  CREATE TABLE "MEDICS"."IDENTIFIED_ANNOTATION" 
   (	"SPAN_ID" NUMBER, 
	"CUI" VARCHAR2(20 BYTE), 
	"POLARITY" NUMBER, 
	"CONDITIONAL" VARCHAR2(1 BYTE), 
	"UNCERTAINITY" NUMBER, 
	"TYPE_ID" NUMBER, 
	"CONFIDENCE" NUMBER, 
	"DISCOVERY_TECHNIQUE" NUMBER, 
	"IDENTIFIED_ANNOTATION_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01" ;

   COMMENT ON COLUMN "MEDICS"."IDENTIFIED_ANNOTATION"."IDENTIFIED_ANNOTATION_ID" IS 'Primary key for identified annotations';
--------------------------------------------------------
--  DDL for Index ONTOLOGYCONCEPTASSIGNMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MEDICS"."ONTOLOGYCONCEPTASSIGNMENT_PK" ON "MEDICS"."IDENTIFIED_ANNOTATION" ("IDENTIFIED_ANNOTATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01" ;
--------------------------------------------------------
--  Constraints for Table IDENTIFIED_ANNOTATION
--------------------------------------------------------

  ALTER TABLE "MEDICS"."IDENTIFIED_ANNOTATION" MODIFY ("IDENTIFIED_ANNOTATION_ID" NOT NULL ENABLE);
  ALTER TABLE "MEDICS"."IDENTIFIED_ANNOTATION" MODIFY ("SPAN_ID" NOT NULL ENABLE);
  ALTER TABLE "MEDICS"."IDENTIFIED_ANNOTATION" ADD CONSTRAINT "ONTOLOGYCONCEPTASSIGNMENT_PK" PRIMARY KEY ("IDENTIFIED_ANNOTATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table IDENTIFIED_ANNOTATION
--------------------------------------------------------

  ALTER TABLE "MEDICS"."IDENTIFIED_ANNOTATION" ADD CONSTRAINT "IDENTIFIED_ANNOTATION_NLP_FK1" FOREIGN KEY ("SPAN_ID")
	  REFERENCES "MEDICS"."NLP_SPAN" ("SPAN_ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger IDENT_ANNO_AUTOINC_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "MEDICS"."IDENT_ANNO_AUTOINC_TRG" 
 BEFORE INSERT ON IDENTIFIED_ANNOTATION
FOR EACH ROW 
BEGIN
  :new.identified_annotation_id := IDENTIFIED_ANNO_SEQ.nextval;
END;

/
ALTER TRIGGER "MEDICS"."IDENT_ANNO_AUTOINC_TRG" ENABLE;




--------------------------------------------------------
--  DDL for Table VALIDATION_ASSIGNMENT
--------------------------------------------------------

  CREATE TABLE "MEDICS"."VALIDATION_ASSIGNMENT" 
   (	"IDENTIFIED_ANNOTATION_ID" NUMBER, 
	"VALIDATION_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01" ;

   COMMENT ON COLUMN "MEDICS"."VALIDATION_ASSIGNMENT"."VALIDATION_ID" IS 'FK to NLP annotation';
--------------------------------------------------------
--  DDL for Index VALIDATION_ASSIGNMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MEDICS"."VALIDATION_ASSIGNMENT_PK" ON "MEDICS"."VALIDATION_ASSIGNMENT" ("IDENTIFIED_ANNOTATION_ID", "VALIDATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01" ;
--------------------------------------------------------
--  Constraints for Table VALIDATION_ASSIGNMENT
--------------------------------------------------------

  ALTER TABLE "MEDICS"."VALIDATION_ASSIGNMENT" MODIFY ("VALIDATION_ID" NOT NULL ENABLE);
  ALTER TABLE "MEDICS"."VALIDATION_ASSIGNMENT" MODIFY ("IDENTIFIED_ANNOTATION_ID" NOT NULL ENABLE);
  ALTER TABLE "MEDICS"."VALIDATION_ASSIGNMENT" ADD CONSTRAINT "VALIDATION_ASSIGNMENT_PK" PRIMARY KEY ("IDENTIFIED_ANNOTATION_ID", "VALIDATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MEDICS_DATA01"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VALIDATION_ASSIGNMENT
--------------------------------------------------------

  ALTER TABLE "MEDICS"."VALIDATION_ASSIGNMENT" ADD CONSTRAINT "IDENTIFIED_ANNOTATION_FK" FOREIGN KEY ("IDENTIFIED_ANNOTATION_ID")
	  REFERENCES "MEDICS"."IDENTIFIED_ANNOTATION" ("IDENTIFIED_ANNOTATION_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "MEDICS"."VALIDATION_ASSIGNMENT" ADD CONSTRAINT "NLP_VALID_ASSIGNMENT_FK" FOREIGN KEY ("VALIDATION_ID")
	  REFERENCES "MEDICS"."NLP_ANNOTATION" ("ANNOTATION_ID") ON DELETE CASCADE ENABLE;
